const mongoose =require("mongoose");
const validator=require("validator");

const PlanterSchema=new mongoose.Schema({
    SKU:{
        type:String,
    required:true},
    name:{
        type:String,
         required:true
    },
    type:{
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true
    },
    varient:{
        s:{
            price:{
                type:Number,
                default:null
            },inches:{
                type:Number,
                default:null
            },quantity:{
                type:Number,
                default:null
            }
        },
        m:{
            price:{
                type:Number,
                default:null
            },inches:{
                type:Number,
                default:null
            }
        },l:{
            price:{
                type:Number,
                default:null
            },inches:{
                type:Number,
                default:null
            }
        }
    },
    description:{
        type:String,
        required:true
    },
    indoorcustomid:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Indoor"
    },outdoorcustomid:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Outdoor"
    },seasonalcustomid:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Seasonal"
    },
    images:[{
        type:String,
    }],
    customImages:[{
          type:String,
        }],
    care:{
        type:String
    },
    quantity:{
        type:Number,
        required:true
    },
    BestSelling:{
        type:Boolean,
        default:false
    },
    date:String
},{  toJSON: { virtuals: true } })
PlanterSchema.virtual('reviews',{
    ref:"CustomerReview",
    localField:'_id',
    foreignField:'Planterid'
})

module.exports= mongoose.model("Planter",PlanterSchema);